# -*- coding: utf-8 -*-
{
    'name': "Insurance Broker System",
    'summary': """Insurance Broker Management & Operations""",
    'description': """Insurance Broker System""",
    'author': "Black Belts Egypt",
    'website': "www.blackbelts-egypt.com",
    'category': 'Industries',
    'version': '0.1',
    'depends': ['base','account','sale','crm','sale_crm','hr',],
    'license': 'AGPL-3',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        # 'reports/report_crm.xml',
        'reports/crm_report_template.xml',
        'reports/claim_report.xml',
        'reports/report_opp_partner.xml',
        'reports/report_agent.xml',
        'data/mail_template_data.xml',
        'views/policy_setup_view.xml',
        'views/endorsement.xml',
        'views/renewal_view.xml',
        'views/claimform_view.xml',
        'views/proposals.xml',
        "views/users_views.xml",
        "views/insurer_partner.xml",
        "views/installments_view.xml",
        "views/views.xml",
        "views/policy_view.xml",
        'views/insured_cargo.xml',
        'views/insured_object.xml',
        'views/insured_vehicle.xml',
        'views/settlements.xml',
        'views/asset_emp.xml',
        'views/invoices_view.xml',
        "views/application_menu.xml",

    ],
    # only loaded in demonstration mode
    'demo': [],
    'images': ['static/src/img/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
